services:
  - type: web
    name: credit-scoring-system
    env: python
    buildCommand: pip install -r requirements.txt && python run.py --train
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
